### PR TITLE
Fix and improve search

### LINKED ISSUE #5: Make search bar to work
Although there is a top search bar, but it does not work at all.  We should implement some search patterns, e.g.:

- [x] Block hash (`ff64cab33a6bca4e7e7cdff4d654fccd617792d49510e8492b81af8d4bcad36d`)
- [ ] Block index (like `#123`?)
- [x] #10 TxID (`ff64cab33a6bca4e7e7cdff4d654fccd617792d49510e8492b81af8d4bcad36d` → this and block hash are both a SHA-256 hexadecimal digest; we need to distinguish two)
- [ ] #9 Account address (`0x561329477ECB990d16a0aB60067d81676d36EE69`)

### LINKED ISSUE #137: Search bar does not work.
When I enter txid into the search bar and press the enter, I got following error:

```
loader.js:195 Uncaught (in promise) Error: 404 page could not be found. Checkout https://www.gatsbyjs.org/docs/add-404-page/
    at loader.js:195
```

### LINKED ISSUE #159: Make search bar redirect to the appropriate item instead of a page
When we're using a hash to navigate to an item, a search page seems like an unnecessary intermediate stage. It can automatically redirect to the appropriate page instead.

### LINKED ISSUE #161: Use absolute path everywhere
`pageContext.endpoint.name` may have to do with this.

### PR DESCRIPTION
**Pull request by tkiapril**
Resolves #5. Resolves #137. Resolves #159. Resolves #161. The root cause of nonfunctional search bar was after e71617841c6953a0ac8e0f5f5d0c18d7b612fe53 where multiple endpoints were supported the search function was not made to point to the correct path.

The following features has been added as well:
 -  Now, searching hash does not point to a search page, but goes to the appropriate page.
 -  Block index search has been added.
 -  Account address search has been added.
 -  Now, all links are made absolute.

### CODE REVIEW

File: src/components/Layout.tsx [hunk 1]
```diff
@@ -70,11 +78,67 @@ interface NavBarProps {
...
-      navigate(`/search/?${value}`);
+      try {
+        const data = await client.query<BlockByHashQuery>({
+          query: BlockByHashDocument,
+          variables: {hash: value},
+        });
+        if (
+          data.data.chainQuery.blockQuery
+          && data.data.chainQuery.blockQuery.block
+          && data.data.chainQuery.blockQuery.block.hash
```
Comment (BasixKOR) [inline src/components/Layout.tsx:93]:
```suggestion
          data.data.chainQuery.blockQuery?.block?.hash
```

Prefer optional chaining if available. Also applies to other usages as well.

File: src/components/Layout.tsx [hunk 2]
```diff
@@ -70,11 +78,67 @@ interface NavBarProps {
...
+  const client = useApolloClient();
+  const onSearch = async (value: string) => {
+    value = value.trim();
     if (value.match(/^[0-9a-fA-F]{64}$/)) {
-      navigate(`/search/?${value}`);
+      try {
+        const data = await client.query<BlockByHashQuery>({
+          query: BlockByHashDocument,
+          variables: {hash: value},
+        });
```
Comment (BasixKOR) [inline src/components/Layout.tsx:89]:
```suggestion
        const data = await client.query<BlockByHashQuery>({
          query: BlockByHashDocument,
          variables: {hash: value},
        }).catch(() => null);
```

Using `Promise.prototype.catch` would be more concise to read.

File: src/components/Layout.tsx (hunk 1 above)
Comment (tkiapril) [reply src/components/Layout.tsx:93]: I tried this, and get something like `optional chaining isn't currently enabled`. Do I have to update something?

**Review by longfin — APPROVED** [review]

File: src/components/Layout.tsx (hunk 2 above)
Comment (tkiapril) [reply src/components/Layout.tsx]: Amended.

File: src/components/Layout.tsx (hunk 1 above)
Comment (tkiapril) [reply src/components/Layout.tsx]: I think it might be better off having this as a separate PR, since there are already 2 more PRs that would be impacted by this change (#162, #170). What do you think?

**Review by BasixKOR — APPROVED** [review]
